controller:
  service:
    targetPorts:
      http: http
      https: http
    enabled: true
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:216989125516:certificate/0f780fc2-6bb7-4d4f-8c3f-c56ba8cd4e88
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    type: LoadBalancer
    externalTrafficPolicy: Local
  config:
    force-ssl-redirect: "true"
    ssl-redirect: "true"






